---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    key_groups:
      - age:
          - age1572dzce9mnf2el3awunkhrr00f2wkvej477lzlm4f0d0l9nt2djq2xg8k2
  - path_regex: cluster/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1572dzce9mnf2el3awunkhrr00f2wkvej477lzlm4f0d0l9nt2djq2xg8k2
